FROM nvidia/cuda:11.3.0-base-ubuntu20.04


# ## Conda Install
RUN apt-get update && \
    apt-get install -y build-essential  && \
    apt-get install -y wget && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN apt -y update &&\
    apt-get -y install vim

# Install miniconda
ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN apt-get update
RUN apt-get install -y wget && rm -rf /var/lib/apt/lists/*
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
# make conda activate command available from /bin/bash --interative shells
RUN conda init bash
RUN conda update -n base -c defaults conda
# Conda Essentials
RUN conda install -n base -c defaults pyyaml typing pillow
# ## PIP
RUN conda install -n base pip

# ##Deep Learning Libraries
# #Pytroch
RUN conda install -n base pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge
# #Tensorflow
RUN conda install  -n base -c conda-forge cudnn=8.1.0
RUN export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
RUN conda run -n base  pip install tensorflow

# ## Datascience Libraries
# # Sklearn, pandas, numpy
RUN  conda install -n base -c conda-forge sklearn-pandas 
# # Seaborn
RUN  conda install -n base -c conda-forge seaborn 
RUN  conda install -n base -c conda-forge xgboost 
RUN  conda install -n base -c conda-forge catboost 

# ## Deepchem $ Transformers
RUN conda install -n base  -c conda-forge deepchem
RUN conda run -n base pip install  transformers 
#RUN conda install -n base pip install --pre deepchem[tensorflow]
RUN conda run -n base pip install --pre deepchem[torch]
RUN conda run -n base pip install simpletransformers

# ##Jupyer Lab
RUN conda install -n base  -c conda-forge jupyterlab
RUN mkdir /app
RUN conda install -n base -c conda-forge jupyterthemes
RUN mkdir -p echo /root/.jupyter/lab/user-settings/@jupyterlab/apputils-extension/ && \
    echo '{ "theme":"JupyterLab Dark" }' > themes.jupyterlab-settings
WORKDIR /app
EXPOSE 8888
ENTRYPOINT ["conda", "run","-n", "base", "jupyter", "lab","--ip=0.0.0.0","--allow-root", "--NotebookApp.token=''","--NotebookApp.password=''"]